version: '3.5'

services:
  kmsm:
    build: kms
    depends_on:
      - tomcat
    image: kms:0
    container_name: kmsm
    sysctls:
      kernel.msgmax: 65536
      kernel.msgmni: 1253
      kernel.msgmnb: 6553600
    privileged: true
    volumes:
      - init_m:/etc
      - cnf_m:/root/config
      - db_m:/root/DB
      - log_m:/root/log
    environment:
      - KMS_NAME=KMSM
      - KMS_PEER=KMSS
      - TZ=${TIMEZONE}
    networks:
      sim_net:
        ipv4_address: 172.16.238.4
    ports:
      - 7000:7000 # CAGTR

  kmss:
    depends_on:
      - tomcat
      - kmsm
    image: kms:0
    container_name: kmss
    sysctls:
      kernel.msgmax: 65536
      kernel.msgmni: 1253
      kernel.msgmnb: 6553600
    privileged: true
    volumes:
      - init_s:/etc
      - cnf_s:/root/config
      - db_s:/root/DB
      - log_s:/root/log
    environment:
      - KMS_NAME=KMSS
      - KMS_PEER=KMSM
      - TZ=${TIMEZONE}
    networks:
      sim_net:
        ipv4_address: 172.16.238.5
    ports:
      - 7001:7000 # CAGTR

volumes:
  init_m:
  init_s:
  cnf_m:
  cnf_s:
  db_m:
  db_s:
  log_m:
  log_s:
