KEMS_IP=$(/usr/bin/host kems | /usr/bin/awk '{print $NF}')
HOST_CONV=$(echo $KMS_NAME | tr '[:upper:]' '[:lower:]')
MY_IP=$(/usr/bin/host $HOST_CONV | /usr/bin/awk '{print $NF}')

/usr/bin/systemctl stop kms

echo "setup.sh $KMS_NAME $MY_MGMT_IP $KEMS_IP"
/root/setup.sh $KMS_NAME $MY_IP $KEMS_IP

echo "systemctl start kms"
/usr/bin/systemctl start kms

echo "pman -d"
/root/bin/pman -d

rm -f /etc/profile.d/custom.sh
