KEMS_IP=$(/usr/bin/host kems | /usr/bin/awk '{print $NF}')

/usr/bin/systemctl stop kms

echo "setup.sh $KMS_NAME $KEMS_IP"
/root/setup.sh $KMS_NAME $KEMS_IP

sed -i -e "s|%PEER_NAME%|$KMS_PEER|" $KMS_HOME/DB/kmsdb_peer.init
sqlite3 $KMS_HOME/DB/kms.db < $KMS_HOME/DB/kmsdb_peer.init

echo "systemctl start kms"
/usr/bin/systemctl start kms

echo "pman -d"
/root/bin/pman -d

rm -f /etc/profile.d/custom.sh
